DROP TABLE IF EXISTS posts CASCADE;

CREATE TABLE posts (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  topic VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  description TEXT,
  external_url VARCHAR(255),
  rating SMALLINT NOT NULL DEFAULT 0,
  likes INTEGER NOT NULL DEFAULT 0,
  date TIMESTAMP
)
